// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTI69l7KUKVMviCVJwd4EOcSbjxPHLIJs',
    appId: '1:198090752268:web:ad0309b239c7b7131d4929',
    messagingSenderId: '198090752268',
    projectId: 'lana-care-15aa7',
    authDomain: 'lana-care-15aa7.firebaseapp.com',
    storageBucket: 'lana-care-15aa7.firebasestorage.app',
    measurementId: 'G-HHB2NZBFSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8fpi2UUjszYsLfNmXAcR2vVXs5vGu3n8',
    appId: '1:198090752268:android:cc4b5de5879a58791d4929',
    messagingSenderId: '198090752268',
    projectId: 'lana-care-15aa7',
    storageBucket: 'lana-care-15aa7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHF0TljNLjajCs232ccoD9jajeI0i0wTU',
    appId: '1:198090752268:ios:e827648af84617981d4929',
    messagingSenderId: '198090752268',
    projectId: 'lana-care-15aa7',
    storageBucket: 'lana-care-15aa7.firebasestorage.app',
    iosClientId: '198090752268-8e8gik0nr2rvaqkl8re93d0gov5fk21t.apps.googleusercontent.com',
    iosBundleId: 'com.example.eloroShopUae',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHF0TljNLjajCs232ccoD9jajeI0i0wTU',
    appId: '1:198090752268:ios:e827648af84617981d4929',
    messagingSenderId: '198090752268',
    projectId: 'lana-care-15aa7',
    storageBucket: 'lana-care-15aa7.firebasestorage.app',
    iosBundleId: 'com.example.eloroShopUae',
  );
}